version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Docker.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
  tests:
    build: 
      context: .
      dockerfile: Docker.dev
    volumes:
      - .:/app
      - /app/node_modules   
    command: ["npm", "run", "test"]
